### ISSUE TITLE
Black options of select box

### ISSUE THREAD

**Issue by p-boiko** [avocode/avocode#1158]
Options of a select box are black: http://screencloud.net/v/5Y5I
Debian Linux, Avocode v2.11.1

**Comment by jakubzitny** [comment]
Hi @p-boiko, thanks for reporting this. We've heard about this problem several times in past few months and we've already fixed it few times but it's quite hard to reproduce it and satisfy all flavors of Linux.

Which GUI are you using? Did you install it with GUI or were you adding it later after the system installation? Is there any chance you're using any special theme in your GUI?

**Comment by p-boiko** [comment]
Hi @jakubzitny 
I'm not sure what devs exactly need to know about my GUI setup. Hope this helps: I use Openbox for managing applications' windows. I have also QT4 and 5, GTK2 and 3.22. I do use custom GTK-theme, but just tried Avocode also with standard Adwaita. I use [this](https://media.avocode.com/download/avocode-app/2.11.1/avocode-app-linux-2.11.1.zip) version of Avocode, but the same issue was found in previous at least two versions.

**Comment by jakubzitny** [comment]
Thanks for the info @p-boiko, that's exactly what we need.

Yes, we use HTML and CSS for GUI, but everything is allright with our styles and it does not happen on other platforms and basic Linux installations. We actually need to install the same or at least a similar platform to investigate this problem.

We hope we'll be able to fix this for the next release of Avocode, we'll keep you updated here 😉

**Comment by skyline94** [comment]
Still have this problem on Ubuntu.
v.2.12.0
Ubuntu 16.04.1 w/ Unity environment.

**Comment by vojtatranta** [comment]
@skyline94 sad though...

Our test machine is `Ubuntu 12.04` dropdowns are white and text is black there.

Can you please tell me which selectboxes exactly cause this? Some of them are our custom, but most of them are system ones.

**Comment by skyline94** [comment]
@vojtatranta seems like every dropdown select(preferences, export dialogs, etc) :( 
Im new with Avocode, but I didn't found any correct dropdown while using. 
Anyway, this is not too big problem for me, because while being hidden selects work fine and tool is absolutely nice^^ made my day over and over)
hope you can fix this trouble as fast as you can)

**Comment by vojtatranta** [comment]
@skyline94 wish I could reproduce it.

We are not styling the dropdown anyhow - because of this, we had similar troubles on windows and we decided to drop styling of select boxes once and for all.

I am afraid I cannot do anything about it right now :(

**Comment by skyline94** [comment]
@vojtatranta i will try to run Avocode on another Ubuntu machine with Unity and with Cinnamon environment. pls wait for feedback here :)

**Comment by vojtatranta** [comment]
@skyline94 waiting!

**Comment by skyline94** [comment]
@vojtatranta same behavior :(

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support

**Comment by p-boiko** [comment]
No, Connor, the issue is still there in the v2.12.
http://screencloud.net/v/nf65

**Comment by vojtatranta** [comment]
@skyline94 what version of Ubuntu?

**Comment by vojtatranta** [comment]
This is apparently Electron / Chromium issue: https://github.com/electron/electron/issues/4322

Wish I could reproduce it... I thought it may be caused by GPU acceleration but we turned it off in Avocode by default.

I'll update on of our virtual machines and get back to you with the news.

**Comment by skyline94** [comment]
@connor-bean no, problem still here. tested on latest version.

**Comment by skyline94** [comment]
@vojtatranta 16.04 i tried to run w/ Unity and Cinnamon environment, both shows black box.

**Comment by skyline94** [comment]
Updated to 2.12.1, issue still here.

**Comment by p-boiko** [comment]
2.12.2 - no fix

**Comment by p-boiko** [comment]
the same with 2.12.3

**Comment by jakubzitny** [comment]
Thanks for the info @p-boiko, I will re-open this issue again. We have not really looked at it for the last two releases.

We have mentioned that we have never been able to reproduce it. So. I am going to install OpenBox on Debian and try to investigate more. You are still using OpenBox, right?

**Comment by p-boiko** [comment]
Ahoj, @jakubzitny !
Thanks for your attention. Yes, my super-laptop keeps me stuck to the lightweight environments :)
So the answer is: yes, Openbox (plus Compton composition manager, AMD APU – might be essential)

**Comment by p-boiko** [comment]
Oops, hit the wrong button... I didn't mean to close the issue.

**Comment by jakubzitny** [comment]
Hi @p-boiko, I tried absolutely minimal Debian installation with Openbox and I played around with some themes. I installed Adwaita from [here](https://www.box-look.org/content/show.php?content=155042) and I was still not able to reproduce the black option background bug.

Here:
<img width="838" alt="screen shot 2017-01-26 at 19 15 24" src="https://cloud.githubusercontent.com/assets/3315662/22344310/fd0de3ee-e3fb-11e6-9fcf-40b94b3b502d.png">

If the theme you use is something else, can you please link it so I can try it? Or if you really want to have this solved, and you have time, can you prepare a virtualbox/vagrant/docker or any other image with your setup? Maybe we will be able to find the root of this problem together.

**Comment by skyline94** [comment]
@jakubzitny i will try to make clean Ubuntu installation in VirtualBox.
in my opinion, problem hides in desktop environments, not in themes. though i will also try to toggle themes.

**Comment by jakubzitny** [comment]
Thanks @skyline94, that will be highly appreciated.

**Comment by skyline94** [comment]
@jakubzitny I made clean Ubuntu installation in Virtual Box and didn't met issue...surprisingly confused. Its really hard to reproduce!
Also i found strange thing...sometimes I can see same black boxes in chrome while surfing, for example, when anchors title tooltip fadein...
All these things looks like video driver problem and because there are a lot of custom drivers for linux issue reproduces only on specific configurations.
Now im gonna try to reinstall some drivers)))

**Comment by jakubzitny** [comment]
Yeah, that's what I thought originally. Can you share with us what video driver are you using, please? And how about you, @p-boiko?

**Comment by p-boiko** [comment]
Fixed for me in v2.14.2
[screenshot](http://screencloud.net/v/5Y0kz)
Can close, if it works for others too

**Comment by jakubzitny** [comment]
Could be. Thanks a lot for the info @p-boiko. Let's close this and let us know if you encounter it (or anything else) again. 😉

**Comment by skyline94** [comment]
Also confirm. its ok now!

**Comment by p-boiko** [comment]
Oh no! They are back with v2.14.6 ;(

**Comment by jakubzitny** [comment]
Damn. Allright, so now we know the problem. We have added some gpu flags. However they caused that for some people the app wouldn't render at all. Like half of it or so. Look at issues #1512 and #1490. I think they have higher priority right now as they were not able to use the app at all. We'll look into this to see if we can satisfy both.

**Comment by jakubzitny** [comment]
Actually @p-boiko, can you please try to launch avocode via one of these commands to see if it helps?

```
./avocode --ignore-gpu-blacklist
./avocode -- --ignore-gpu-blacklist
```

**Comment by p-boiko** [comment]
yes, this works :)
updated app's shortcut. Thanks!

**Comment by jakubzitny** [comment]
Allright, let's close this again and keep this as a workaround.
Is it the first one that is working or the second command with extra `--`?

**Comment by p-boiko** [comment]
First command. Didn't try the second, cause not sure what empty parameter can do, and the first command works :)

**Comment by skyline94** [comment]
2.14.6 no black boxes from 2.14.2
