### ISSUE TITLE
Sketch designs with a lot of artboards fails to upload

### ISSUE THREAD

**Issue by galkinrost** [avocode/avocode#500]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.3 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/galkinrost/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Hey so far we can reproduce this problem by:
1. Opening any design that hasn't been synced before and syncing it to avocode
2. After the sync is completed, ignore the assign dialog in browser and go back to sketch
3. Close the plugin and open it again
4. Choose "Sync as a new design"

Restarting sketch would fix the issue. Did you sync some design twice in a row as well as a new design? Or how did the error happen?

**Comment by galkinrost** [comment]
The problem is that plugin doesn't open browser after crashing. I could share my sketch file to in private, if you give me your email.

**Comment by rychlis** [comment]
hey please share the file with us at team@avocode.com

Did you sync some design twice in a row as well as a new design? Or how did the error happen?

**Comment by galkinrost** [comment]
After reinstalling plugin and removing all designs in my avocode project, I do:

1. Open sketch.
2. Run avocode Plugin
3. Push "Sync to Avocode"
4. Wait.
5. After last step "Uploading" I get this error.

That's it. 
Send from r.galkin@babo.com

**Comment by macpheedesign** [comment]
I'm having the same issue.
sketch-plugin-mac-2.1.4
Sketch Version 3.4 (15588)

**Comment by rychlis** [comment]
@macpheedesign could you report the error as a new issue please? How much artboards does your document have? Could you send the file to team@avocode.com if possible? Thanks

**Comment by rychlis** [comment]
We have just released first beta version of the new extension. See this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by rychlis** [comment]
We've released a new beta version: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#300-prerelease2

This one will allow you to sync just one artboard at a time so you can prioritize which artboard do you need.

This is a duplicate of #513 I think, I am leaving just #513 open

**Comment by macpheedesign** [comment]
Thanks

Excuse typos and brevity - sent from my mobile device.

**Comment by galkinrost** [comment]
@rychlis Could you please extend my trial for 2 days r.galkin@babo.com so I can check the improvements?

**Comment by rychlis** [comment]
@galkinrost done :) If anyone else needs a trial extension, give us an email at team@avocode.com

**Comment by galkinrost** [comment]
Thanks! We installed beta plugin, but it's still not working. Window with artboards opens, but I can't select any item. Only if i click right button and then left item becomes selected. The same issue with others buttons.

**Comment by rychlis** [comment]
That problem is some kind of Safari glitch in OSX Yosemite, see https://github.com/avocode/avocode/issues/549

Another possible (and probably more easy) workaround is to open the plugin in Sketch first (as you would normally) and then open this location in your browser (e.g. Safari): http://127.0.0.1:33162/panel/

Important note: the extension window must be opened simultaneously for the whole time

**Comment by galkinrost** [comment]
It works, but after syncing is finished I doesn't see my artboards in avocode(even after reload).

**Comment by rychlis** [comment]
@galkinrost could you please send us the sketch-panels.log as per [Reporting bugs](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#reporting-bugs) instructions? Thanks

**Comment by galkinrost** [comment]
@rychlis Done!
